# Generated by Django 3.2 on 2022-11-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userbot', '0024_alter_day_lesson_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Day_lesson',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Teacher_lesson',
        ),
    ]
