# Generated by Django 3.2 on 2022-11-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'ordering': ['id'], 'verbose_name': 'пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(default=10.0, max_length=30, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_push_maker',
            field=models.BooleanField(default=False, verbose_name='Создатель пуш сообщений'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='is_respondent',
            field=models.BooleanField(default=False, verbose_name='Получатель сообщений "задать вопрос"'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(default=10.0, max_length=30, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='tg_name',
            field=models.CharField(max_length=30, verbose_name='Имя в телеграме'),
        ),
    ]
