# Generated by Django 3.2 on 2022-11-25 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0002_auto_20221125_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='reg_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_respondent',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
    ]
