# Generated by Django 3.2 on 2022-11-30 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0003_auto_20221125_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('cost', models.CharField(blank=True, max_length=150, null=True, verbose_name='Стоимсоть')),
                ('size', models.CharField(blank=True, max_length=150, null=True, verbose_name='Рвзмер')),
                ('link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка')),
                ('photo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фото')),
                ('insure', models.CharField(blank=True, max_length=150, null=True, verbose_name='Страховка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='telegram_users.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'ordering': ('order',),
            },
        ),
    ]
