# Generated by Django 3.2 on 2022-12-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_yuany', models.IntegerField(blank=True, null=True, verbose_name='Коэф-т к курсы')),
                ('k_comis_1', models.IntegerField(blank=True, null=True, verbose_name='Коммиссия 1')),
                ('k_comis_2', models.IntegerField(blank=True, null=True, verbose_name='Коммиссия 2')),
            ],
            options={
                'verbose_name': 'Настройки',
            },
        ),
    ]
