# Generated by Django 3.2 on 2022-12-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_users', '0006_alter_settings_k_yuany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
